spring:
  application:
    name: File Storage
  datasource:
    url: jdbc:h2:file:./file-storage
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 128KB
      max-file-size: 16MB
      max-request-size: 16MB
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
file_store:
  path:
    root: /Users/sergeishaikin/Documents/Files